name: Funding Rate History Update

on:
  schedule:
    # Run at 14:00 UTC (22:00 UTC+8)
    - cron: '0 14 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-funding-rates:
    runs-on: ubuntu-latest-4
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Update Bitget funding rates
        run: python update_funding_rates_bitget.py

      - name: Update Binance funding rates
        run: python update_funding_rates_binance.py

      - name: Update last updated date in README
        run: |
          # Get current date in format YYYY-MM-DD HH:MM UTC+8
          CURRENT_DATE=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M %Z')
          # Replace the line with last updated date in README.md
          sed -i "s|<!-- LAST_UPDATED -->.*<!-- /LAST_UPDATED -->|<!-- LAST_UPDATED -->Funding Rate History Last Updated: $CURRENT_DATE<!-- /LAST_UPDATED -->|g" README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/ README.md
          git commit -m "Update funding rates history ($(date '+%Y-%m-%d'))" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 